version: '3'
services:
  web:
    build: .    # Build context is the current directory
    ports:
      - "3000:3000"  # Map host port to container port
    volumes:
      - .:/usr/src/app  # Mount the current directory into the container
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAX_RETRY=3
